package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;


    @PostMapping(path="/signup", consumes = "application/json")
    public  @ResponseBody String signup(@RequestBody User user) {
        // Check if a user with the same email already exists
        if (userRepository.existsByEmail(user.getEmail())) {
            return ("User with this email already exists");
        }
        // If the email doesn't exist, save the user
        userRepository.save(user);

        return "success";
    }

    @PostMapping(path="/login", consumes = "application/json")
    public @ResponseBody String login(@RequestBody User user) {
        if(userRepository.existsByEmail(user.getEmail())){
            if(userRepository.password(user.getEmail()).equals(user.getPassword())){
                return "success";
            }
            return "pass incorrect";
        }
        return "email incorrect";
    }
}